version: '3.9'

services:
  notely-db:
    image: mongo:latest
    container_name: notely-db
    restart: always
    env_file:
      - ./.env.local
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
    networks:
      - notely-network

volumes:
  mongodata:

networks:
  notely-network:
    driver: bridge
